### PR TITLE
fix: Dependency update

### PR DESCRIPTION
**Pull request by DanyHenriquez**
- Go version update (1.19)
- Dependency updates (go.mod/go.sum)

I think it would be a great idea to add Renovate to update dependencies automatically. Patches and security updates should always be merged as soon as possible.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@DanyHenriquez plz fix:

图片

**Comment by DanyHenriquez** [comment]
@hsluoyz 

Of course. Will do. Maybe i can also help with Renovate or has a dependency update mechanism been considered? Has it been decided against?

**Comment by hsluoyz** [comment]
@DanyHenriquez we don't have plan to enable dependabot for now. It's too noisy (as we have hundreds of repos) and sometimes buggy :(

**Comment by DanyHenriquez** [comment]
@hsluoyz That is why I proposed Renovate and not Dependabot.

Dependabot is horrible for bigger projects with many repos. I know this from experience, but in the company i work for we also have many repos, because microservices and Renovate works wonders there.

Would be nice to investigate. Letting security updates go just because only Dependabot was considered and it was noisy might not be the best idea.

Look into Renovate if you want something suitable for many repos.

Just my 2 cents. Do with it as you will.

Looking into the issue with the tests now.

**Comment by hsluoyz** [comment]
@DanyHenriquez still faulty after multiple runs. Can you fork this repo and try at your own repo to make sure it works, then make a PR here? It's inconvenient here because every time you push, it asks the maintainers to click a button to start CI.

Closed here for now.

**Pull request closed without merging**
